apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: vj8vx6bdl-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:1a9c428ae264bac12d37efd4bc55573df8b60421@sha256:4fff76a4fe462a2ab35226fc4e9f3fa853c9a85e7fb13fe42ff943d0e5460e26
        name: container-image  
